import type { Item } from "./types";

/**
 * LOSTNET SEED DATASET
 * --------------------
 * One focused geographic area: Indiranagar, Bengaluru (100 Feet Road area).
 *
 * Design intent (quality over quantity) — verify with `npm run report`:
 *   - 1 CLEAN match:    lost Honda key <-> found black car key (≈350 m, same day)  → ~79%
 *   - 2 AMBIGUOUS:      earbud pair (≈340 m, 30 h) → ~69%; bag pair (≈1 km, 15 h) → ~65%
 *   - 2 NEAR-MISS:      keys pair and jewelry pair — same category but must score
 *                       BELOW threshold (0.60). Guarded by matcher tests.
 *   - Several UNRELATED items to prove the engine says no.
 *
 * Items sit on a wide enough spread that markers don't overlap at board zoom;
 * only designed pairs are close together (see the marker notes in context.md).
 *
 * Coordinates are real-ish for the neighborhood; timestamps are fixed ISO
 * strings so matcher scores are deterministic and testable.
 */

export const SEED_CENTER = { lat: 12.9719, lng: 77.6408 };

export const SEED_ITEMS: Item[] = [
  // ---- The clean demo match -------------------------------------------------
  {
    _id: "lost-01",
    kind: "lost",
    title: "Black Honda key with a red tag",
    description: "Black car key with a small red 'R' keychain. Dropped somewhere while walking down 100 Feet Road after dinner.",
    categoryId: "keys",
    placeLabel: "100 Feet Road, near the café",
    location: { lat: 12.9719, lng: 77.6408 },
    occurredAt: "2026-09-28T18:00:00.000Z",
    reportedAt: "2026-09-28T18:42:00.000Z",
    colors: ["black", "red"],
    materials: ["metal"],
    status: "open",
  },
  {
    _id: "found-01",
    kind: "found",
    title: "Found black car key",
    description: "Black car key with a red tag, picked up near the Sony World signal this morning.",
    categoryId: "keys",
    placeLabel: "Sony World Signal",
    location: { lat: 12.9731, lng: 77.6415 },
    occurredAt: "2026-09-29T09:00:00.000Z",
    reportedAt: "2026-09-29T09:35:00.000Z",
    colors: ["black", "red"],
    materials: ["metal"],
    status: "open",
  },

  // ---- Ambiguous pair #1: bags ---------------------------------------------
  {
    _id: "lost-02",
    kind: "lost",
    title: "Grey backpack with a laptop",
    description: "Grey canvas backpack. Work laptop inside, plus a notebook and a charger. Left it in an auto on CMH Road.",
    categoryId: "bag",
    placeLabel: "CMH Road auto stand",
    location: { lat: 12.9745, lng: 77.6368 },
    occurredAt: "2026-09-27T21:30:00.000Z",
    reportedAt: "2026-09-27T22:05:00.000Z",
    colors: ["grey"],
    materials: ["canvas"],
    status: "open",
  },
  {
    _id: "found-02",
    kind: "found",
    title: "Grey bag at the bus stop",
    description: "Grey shoulder bag left on the bench at the Double Road bus stop.",
    categoryId: "bag",
    placeLabel: "Double Road bus stop",
    location: { lat: 12.9689, lng: 77.6435 },
    occurredAt: "2026-09-28T12:15:00.000Z",
    reportedAt: "2026-09-28T12:40:00.000Z",
    colors: ["grey"],
    materials: [],
    status: "open",
  },

  // ---- Ambiguous pair #2: earbuds --------------------------------------------
  {
    _id: "lost-03",
    kind: "lost",
    title: "White earbud — right side",
    description: "One white wireless earbud, right side only. Fell out of my pocket while cycling near Defence Colony.",
    categoryId: "electronics",
    placeLabel: "Defence Colony park entrance",
    location: { lat: 12.9677, lng: 77.6351 },
    occurredAt: "2026-09-26T07:40:00.000Z",
    reportedAt: "2026-09-26T08:10:00.000Z",
    colors: ["white"],
    materials: ["plastic"],
    status: "open",
  },
  {
    _id: "found-03",
    kind: "found",
    title: "Single white earbud",
    description: "Found a single white earbud on the footpath, still in its silicone tip.",
    categoryId: "electronics",
    placeLabel: "5th Cross footpath",
    location: { lat: 12.9703, lng: 77.6335 },
    occurredAt: "2026-09-27T14:00:00.000Z",
    reportedAt: "2026-09-27T14:20:00.000Z",
    colors: ["white"],
    materials: ["plastic", "silicon"],
    status: "open",
  },

  // ---- Near-miss pair: jewelry (should NOT match — different sub-kind) --------
  {
    _id: "lost-04",
    kind: "lost",
    title: "Silver bracelet",
    description: "Thin silver bracelet, plain, no charms. Lost while walking back from the gym.",
    categoryId: "jewelry",
    placeLabel: "6th Main, near the gym",
    location: { lat: 12.9752, lng: 77.6442 },
    occurredAt: "2026-09-25T20:00:00.000Z",
    reportedAt: "2026-09-25T20:30:00.000Z",
    colors: ["silver"],
    materials: ["metal"],
    status: "open",
  },
  {
    _id: "found-04",
    kind: "found",
    title: "Silver chain necklace",
    description: "Silver chain necklace found on the footpath. Has a tiny pendant.",
    categoryId: "jewelry",
    placeLabel: "80 Feet Road",
    location: { lat: 12.9798, lng: 77.6451 },
    occurredAt: "2026-09-29T11:00:00.000Z",
    reportedAt: "2026-09-29T11:25:00.000Z",
    colors: ["silver"],
    materials: ["metal"],
    status: "open",
  },

  // ---- Unrelated items --------------------------------------------------------
  {
    _id: "lost-05",
    kind: "lost",
    title: "Tabby cat, answers to 'Simba'",
    description: "Orange tabby, white paws, green collar. Slipped out of the gate near the metro station.",
    categoryId: "pet",
    placeLabel: "Indiranagar Metro Station",
    location: { lat: 12.9783, lng: 77.6410 },
    occurredAt: "2026-09-29T06:30:00.000Z",
    reportedAt: "2026-09-29T07:00:00.000Z",
    colors: ["orange", "white"],
    materials: [],
    status: "open",
  },
  {
    _id: "found-05",
    kind: "found",
    title: "Blue umbrella",
    description: "Blue folding umbrella left at the juice shop counter.",
    categoryId: "other",
    placeLabel: "Metro station juice shop",
    location: { lat: 12.9775, lng: 77.6415 },
    occurredAt: "2026-09-28T17:20:00.000Z",
    reportedAt: "2026-09-28T17:45:00.000Z",
    colors: ["blue"],
    materials: ["nylon"],
    status: "open",
  },
  {
    _id: "lost-06",
    kind: "lost",
    title: "Passport in a brown folder",
    description: "Brown paper folder containing a passport. Last seen at the printing shop.",
    categoryId: "documents",
    placeLabel: "12th Main printing shop",
    location: { lat: 12.9701, lng: 77.6374 },
    occurredAt: "2026-09-27T15:10:00.000Z",
    reportedAt: "2026-09-27T15:40:00.000Z",
    colors: ["brown"],
    materials: ["paper"],
    status: "open",
  },
  {
    _id: "found-06",
    kind: "found",
    title: "Running shoes, size 9",
    description: "Pair of blue running shoes left by the badminton court.",
    categoryId: "sports",
    placeLabel: "Kanteerava court gate",
    location: { lat: 12.9740, lng: 77.6470 },
    occurredAt: "2026-09-26T19:00:00.000Z",
    reportedAt: "2026-09-26T19:30:00.000Z",
    colors: ["blue"],
    materials: [],
    status: "open",
  },
  {
    _id: "lost-07",
    kind: "lost",
    title: "Maroon college cap",
    description: "Maroon cap with the college logo stitched on the front.",
    categoryId: "clothing",
    placeLabel: "CMH Road book store",
    location: { lat: 12.9738, lng: 77.6371 },
    occurredAt: "2026-09-25T16:45:00.000Z",
    reportedAt: "2026-09-25T17:10:00.000Z",
    colors: ["maroon"],
    materials: ["cotton"],
    status: "open",
  },
  {
    _id: "found-07",
    kind: "found",
    title: "Power bank, 10000 mAh",
    description: "Black power bank found on a café table, still half charged.",
    categoryId: "electronics",
    placeLabel: "Third Wave café, 80 Feet Road",
    location: { lat: 12.9771, lng: 77.6454 },
    occurredAt: "2026-09-29T14:30:00.000Z",
    reportedAt: "2026-09-29T15:00:00.000Z",
    colors: ["black"],
    materials: ["plastic"],
    status: "open",
  },
  {
    _id: "lost-08",
    kind: "lost",
    title: "Blue helmet with a sticker",
    description: "Blue scooter helmet, white scratch on the left side, a 'Bangalore FC' sticker on the back.",
    categoryId: "sports",
    placeLabel: "ESI Hospital parking",
    location: { lat: 12.9655, lng: 77.6420 },
    occurredAt: "2026-09-28T10:00:00.000Z",
    reportedAt: "2026-09-28T10:25:00.000Z",
    colors: ["blue", "white"],
    materials: ["plastic"],
    status: "open",
  },
  {
    _id: "found-08",
    kind: "found",
    title: "Reading glasses, black frame",
    description: "Black rectangular reading glasses found in the park, on a bench.",
    categoryId: "glasses",
    placeLabel: "Defence Colony park bench",
    location: { lat: 12.9679, lng: 77.6348 },
    occurredAt: "2026-09-27T08:30:00.000Z",
    reportedAt: "2026-09-27T09:00:00.000Z",
    colors: ["black"],
    materials: ["plastic", "glass"],
    status: "open",
  },
  {
    _id: "lost-09",
    kind: "lost",
    title: "Bunch of keys on a carabiner",
    description: "House keys and a small flashlight on a silver carabiner clip.",
    categoryId: "keys",
    placeLabel: "Double Road crossing",
    location: { lat: 12.9682, lng: 77.6428 },
    occurredAt: "2026-09-27T19:10:00.000Z",
    reportedAt: "2026-09-27T19:40:00.000Z",
    colors: ["silver"],
    materials: ["metal"],
    status: "open",
  },
  {
    _id: "found-09",
    kind: "found",
    title: "Found a single house key",
    description: "Single brass house key found near the footpath drain.",
    categoryId: "keys",
    placeLabel: "Ulsoor lake road",
    location: { lat: 12.984, lng: 77.662 },
    occurredAt: "2026-09-28T08:10:00.000Z",
    reportedAt: "2026-09-28T08:30:00.000Z",
    colors: ["gold"],
    materials: ["metal"],
    status: "open",
  },
  {
    _id: "lost-10",
    kind: "lost",
    title: "Yellow rain jacket",
    description: "Bright yellow rain jacket, rolled up, left under a restaurant table.",
    categoryId: "clothing",
    placeLabel: "CMH Road restaurant lane",
    location: { lat: 12.9752, lng: 77.6366 },
    occurredAt: "2026-09-29T00:10:00.000Z",
    reportedAt: "2026-09-29T00:40:00.000Z",
    colors: ["yellow"],
    materials: ["nylon"],
    status: "open",
  },
  {
    _id: "found-10",
    kind: "found",
    title: "Found wallet, no cards inside",
    description: "Brown leather wallet found empty on the footpath, no cards or cash inside.",
    categoryId: "wallet",
    placeLabel: "Double Road footpath",
    location: { lat: 12.9685, lng: 77.6378 },
    occurredAt: "2026-09-28T09:45:00.000Z",
    reportedAt: "2026-09-28T10:00:00.000Z",
    colors: ["brown"],
    materials: ["leather"],
    status: "open",
  },
];
